[common_split]
rule1=["[^0-9 ]\\.\\s*", "\\d"]
rule2=["[<\\[]\\uE105\\s*\\d+[>\\]]", ""]
rule3=["[\\.!?]\\s*", "-"]
rule5=["\\.\\s*", "[a-z]"]
rule6=["^\\s*[\\-\\*]+", ""]

[common_not_split]
rule1=["(?i)\\b(\\(?mm|cm|dm|m|km|mg|cg|dg|g|gr|kg|max|min|fig)\\.\\uE105?\\s*\\d",""]
rule2=["\\b([A-Z0-9]\\.)+\\uE105\\s*",""]
rule3=["^(?i)\\s*(([0-9]+|[ivx]+|\\w)\\.\\uE105?\\s*)+",""]
rule4=["(?i)(https?|ftp)://[^\\s/$.?#].[^\\s]*\\?\\uE105[^\\s]+",""]
rule5=["\\b(Co)\\.\\uE105?\\s*Ltd",""]
rule6=["(?i)\\b(tel|fax|cell?)\\.\\uE105?\\s*[\\d+\\(\\) ]",""]
rule7=["\\b[a-z]\\.\\uE105?\\s*",""]
rule8=["(?i)\\b(No|Nos|Nr|Art|pp|pag|vol|chap|fig|figs|approx)\\.\\uE105?\\s*\\d",""]
rule9=["[?!]\\)\\uE105\\s*[a-z]",""]
rule10=["(?i)\\b(Adj|Adm|Adv|Asst|Bart|Bldg|Brig|Bros|Capt|Cmdr|Col|Comdr|Con|Corp|Cpl|DR|Dr|Drs|Ens|Gen|Gov|Hon|Hr|Hosp|Insp|Lt|MM|MR|MRS|MS|Maj|Messrs|Mlle|Mme|Mr|Mrs|Ms|Msgr|Op|Ord|Pfc|Ph|Prof|Pvt|Rep|Reps|Res|Rev|Rt|Sen|Sens|Sfc|Sgt|Sr|St|Supt|Surg|vs|rev)\\.\\uE105?\\s*",""]
rule11=["((?:(https?|s?ftp)[:：]\\/\\/)|(?:www\\.\\uE105?))((?:(?:[A-Z0-9][A-Z0-9-]{0,61}[A-Z0-9]\\.\\uE105?)+)([A-Z]{2,6})|(?:\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}))(?::(\\d{1,5}))?(?:(\\/[!-~]+)*)\\/?",""]

[zh_split]
rule1=["([\\.\\!\\?“”！，。？、]\\uE105)?\\s*([…]+\\s+)*…+[\"”’！，。？、\\.\\!\\?]*",""]

[en_split]
rule1=["([…]+\\s+)*…+(([\"”’]+))", ""]
rule2=["","\\[[^\\[\\]]+\\]\\uE105?$"]

[en_not_split]
rule1=["(Jan.|Feb.|Mar.|Apr.|May.|Jun.|Jul.|Aug.|Sep.|Oct.|Nov.|Dec.)\\uE105?\\s*",""]
